### arguments: https://llamafactory.readthedocs.io/en/latest/advanced/arguments.html

### model
model_name_or_path: Qwen/Qwen3-1.7B
trust_remote_code: true

### method
stage: sft
do_train: true
disable_shuffling: false
finetuning_type: full
deepspeed: examples/deepspeed/ds_z0_config.json # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: sunny_reasoning
template: qwen3
# full list of available chat-templates
# from src.llamafactory.data.template import TEMPLATES
# for name in sorted(TEMPLATES.keys()):
#     print(name)
cutoff_len: 16384 # 8192, 8192*4, 8192*2
max_samples: 50000
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen3-4b/full/sft
logging_steps: 1
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2 # global_batch = bs x D x a 128,256 (step > 700)
learning_rate: 4.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
# full list of available optimizers
# from transformers.training_args import OptimizerNames
# print("\n".join([x.value for x in OptimizerNames]))
optim: adamw_torch_fused #adam -> adamw -> adafactor, 4bit-optim

### acceleration
flash_attn: fa2
enable_liger_kernel: true
disable_gradient_checkpointing: true

### eval
# eval_dataset: alpaca_en_demo
val_size: 0.05
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
